
FROM docker:latest

# 安装 Go 编译环境依赖
RUN apk add --no-cache gcc
RUN apk add --no-cache musl-dev
RUN apk add --no-cache go

# 安装 Python 环境
RUN apk add --no-cache python3
RUN apk add --no-cache py3-pip

# 安装 Python 依赖
RUN pip3 install pyyaml
