name: Check TeleYard

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"  # 设置 Go 版本为 1.22

      - name: Install dependencies
        run: |
          go mod tidy  # 更新并安装所有依赖

      - name: Run tests
        run: |
          go test ./... -v  # 运行所有测试
